### ISSUE TITLE
[功能请求] 是否可以支持配置显示热搜条数和双列显示样式

### ISSUE THREAD

**Issue by FlechazoPh** [Honye/scriptable-scripts#1]
是否可以支持配置显示热搜条数和双列显示样式

条数大于7条，如图：
![6C6CE000-9F40-42E7-9AEA-DAACFB913444](https://user-images.githubusercontent.com/94276146/202149455-2bb154c5-aa78-44c8-a2a2-c1e22871ac6a.jpeg)

仿照官方的双列热搜显示，如图：

![C8C55494-D45C-4F45-8F4A-E61118A73D06](https://user-images.githubusercontent.com/94276146/202149501-019d2a10-f593-4630-abf5-fb8f8c61ce7a.jpeg)

**Comment by Honye** [comment]
已支持多列显示
