### ISSUE TITLE
Shortcuts不适配iphone14pro

### ISSUE THREAD

**Issue by Anber55** [Honye/scriptable-scripts#5]
希望能尽快适配，感谢，或者增加纯色背景也行。希望能有一个小组件的快捷启动

能在scriptable里展示，但不能放到桌面
![60F2C40C-EF38-4A9D-88B7-B216670123E4](https://user-images.githubusercontent.com/117334130/204010494-3428e8b5-772b-4412-af51-080bc90a0b19.jpeg)
![F182692C-9C23-42D8-BC80-54A9A2EE3011](https://user-images.githubusercontent.com/117334130/204010508-4918c471-1b11-47ab-bb54-e1ecbfc9f480.jpeg)

**Comment by Honye** [comment]
已修复 https://github.com/Honye/scriptable-scripts/commit/8e27cc7a0e5d59d198a2a6e0741484ef4a5e0dc9
