### ISSUE TITLE
使用bridge调用enter后的数据

### ISSUE THREAD

**Issue by CokeLau** [Honye/scriptable-scripts#8]
`input.addListener('keydown',function(event){
if(event === 'Enter'){
()=>ScriptableBridge{'alert',input.value
}
}
}`

我是这样做的，但是好像不能这样cb，请问怎么做到？谢谢大佬

**Comment by Honye** [comment]
语法错误，看示例

**Comment by CokeLau** [comment]
新手= =，改用了change可以了
遇到了新问题，好像不能在里面用req

**Comment by Honye** [comment]
HTML 里使用 Web API，不能直接使用 Scriptable API
